require: rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  Exclude:
    - "gemfiles/**/*"
    - "vendor/**/*"

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "spec/support/*"

Metrics/PerceivedComplexity:
  Max: 20

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

RSpec/DescribeClass:
  Exclude:
    - "spec/integration/**/*_spec.rb"

RSpec/ExpectInHook:
  Enabled: false

RSpec/EmptyLineAfterHook:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - cloudtasker.gemspec
    - "spec/**/*"

Style/Documentation:
  Exclude:
    - "examples/**/*"
    - "spec/**/*"

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/CyclomaticComplexity:
  Max: 15

Lint/EmptyBlock:
  Exclude:
    - "examples/rails/config/routes.rb"

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - "examples/**/*"
    - "spec/integration/**/*"

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NoExpectationExample:
  AllowedPatterns:
    - ^expect_
    - ^assert_

RSpec/IndexedLet:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/VerifiedDoubles:
  Exclude:
    - spec/cloudtasker/cloud_task_spec.rb
    - spec/cloudtasker/backend/google_cloud_task_v1_spec.rb
    - spec/cloudtasker/backend/google_cloud_task_v2_spec.rb
