# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.1.3'

gem 'puma', '~> 5.6.7'

# Background jobs via Cloud Tasks
gem 'cloudtasker', github: 'keypup-io/cloudtasker'

# Active record adapter
gem 'sqlite3'

group :development do
  gem 'foreman'
end
