# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.1.3'

gem 'puma', '~> 5.3.2'

# Background jobs via Cloud Tasks
gem 'cloudtasker', path: '../../'

# Active record adapter
gem 'sqlite3'
