# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.2'

# Background jobs via Cloud Tasks
gem 'cloudtasker', path: '../../'

# Active record adapter
gem 'sqlite3'
