# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.5'

# Web framework
gem 'sinatra'

# Background jobs via Cloud Tasks
gem 'cloudtasker', path: '../../'
