# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.0.0'

# Server
gem 'puma'

# Web framework
gem 'sinatra'

# Background jobs via Cloud Tasks
gem 'cloudtasker', path: '../../'

group :development do
  gem 'foreman'
end
